# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: VKP Virtual Kubernetes Platform
theme:
  name: material
  features:
    - content.code.annotate
    - navigation.instant
    - navigation.tabs
    - navigation.tracking
repo_name: vkp-app/vkp
repo_url: https://github.com/vkp-app/vkp
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences